#!/bin/bash
set +x

INPUT_FILE_ABS=$(python -c "import os; print(os.path.realpath('$1'))")

if [[ -d $INPUT_FILE_ABS ]]; then
  INPUT_FILE_ABS=$INPUT_FILE_ABS/$(basename -- "$INPUT_FILE_ABS").fa.struct.fa
fi

shift
FILE_NAME=$(basename -- "$INPUT_FILE_ABS")
DATA_DIR=$(dirname -- "$INPUT_FILE_ABS")

pushd "$DATA_DIR"

# PYTHONPATH="../../aptamer:$PYTHONPATH" mprof run --python --include-children python ../../aptamer/create_graph.py $FILE_NAME $@
python ../../aptamer/create_graph.py $FILE_NAME $@

popd

