#!/bin/bash
set -x

INPUT_FILE_ABS=$(python -c "import os; print(os.path.realpath('$1'))")
shift
FILE_NAME=$(basename -- "$INPUT_FILE_ABS")
DATA_DIR=$(dirname -- "$INPUT_FILE_ABS")

pushd "$DATA_DIR"

python ../../src/create_graph.py $FILE_NAME $@

popd

