#!/bin/bash
set +x
set -e

INPUT_FILE_ABS=$(python -c "import os; print(os.path.realpath('$1'))")
shift
FILE_NAME=$(basename -- "$INPUT_FILE_ABS")
DATA_DIR=${DATA_DIR:-./data}
DATA_NAME="${FILE_NAME%.*}"
SCRIPT_PATH=${SCRIPT_PATH:-../../aptamer}

echo "Creating data dir $DATA_NAME"
mkdir -p "$DATA_DIR/$DATA_NAME"
pushd "$DATA_DIR/$DATA_NAME"

cp $INPUT_FILE_ABS ./$FILE_NAME

python $SCRIPT_PATH/predict_structures.py $FILE_NAME $@

popd

